/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import MVP.ILobby;
import MVP.LobbyPresenter;

/**
 *
 * @author usuario
 */
public class FrmLobby extends javax.swing.JFrame {

    ILobby presenter = new LobbyPresenter();
    /**
     * Creates new form FrmLobby
     */
    public FrmLobby() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        lblJugador = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        lblNombre2 = new javax.swing.JLabel();
        lblNombre3 = new javax.swing.JLabel();
        lblNombre4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 153, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFondo.setBackground(new java.awt.Color(0, 102, 51));
        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJugador.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        lblJugador.setForeground(new java.awt.Color(255, 255, 255));
        lblJugador.setText("LOBBY");
        pnlFondo.add(lblJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        lblNombre1.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        lblNombre1.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre1.setText("...");
        pnlFondo.add(lblNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        btnSalir.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        pnlFondo.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));

        lblNombre2.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        lblNombre2.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre2.setText("...");
        pnlFondo.add(lblNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        lblNombre3.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        lblNombre3.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre3.setText("...");
        pnlFondo.add(lblNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        lblNombre4.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        lblNombre4.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre4.setText("...");
        pnlFondo.add(lblNombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        getContentPane().add(pnlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 460, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    public void abrirPantLobby(){
       this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblJugador;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblNombre3;
    private javax.swing.JLabel lblNombre4;
    private javax.swing.JPanel pnlFondo;
    // End of variables declaration//GEN-END:variables
}
