/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import MVP.IConfPartida;
import javax.swing.JOptionPane;

/**
 *
 * @author alexa
 */
public class FrmConfPartida extends javax.swing.JFrame {

    IConfPartida presenter;
    
    /**
     * Creates new form FrmConfPartida
     * @param presenter
     */
    public FrmConfPartida(IConfPartida presenter) {
        this.presenter = presenter;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        lblConf = new javax.swing.JLabel();
        lblCantFichas = new javax.swing.JLabel();
        lblCantJug = new javax.swing.JLabel();
        cbxFichas = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        cbxJugadores = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configuración de la partida");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFondo.setBackground(new java.awt.Color(0, 102, 51));
        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblConf.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        lblConf.setForeground(new java.awt.Color(255, 255, 255));
        lblConf.setText("Configuración de la partida");
        pnlFondo.add(lblConf, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 44, -1, -1));

        lblCantFichas.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        lblCantFichas.setForeground(new java.awt.Color(255, 255, 255));
        lblCantFichas.setText("Cantidad de fichas (2-7)");
        pnlFondo.add(lblCantFichas, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 124, -1, -1));

        lblCantJug.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        lblCantJug.setForeground(new java.awt.Color(255, 255, 255));
        lblCantJug.setText("Cantidad de jugadores");
        pnlFondo.add(lblCantJug, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 124, -1, -1));

        cbxFichas.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        cbxFichas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7" }));
        pnlFondo.add(cbxFichas, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 171, -1, -1));

        btnGuardar.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        pnlFondo.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 337, -1, -1));

        cbxJugadores.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        cbxJugadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        cbxJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxJugadoresActionPerformed(evt);
            }
        });
        pnlFondo.add(cbxJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 179, -1, -1));

        getContentPane().add(pnlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        this.selectGuardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cbxJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxJugadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxJugadoresActionPerformed
    
    /**
     * Método que abre la pantalla de configuración partida
     */
    public void abrirPantConf() {
        this.setVisible(true);
    }
    
    /**
     * Método que indica que guarda la configuración de la partida
     */
    public void selectGuardar() {
        try {
        this.dispose();
        int cantFichas = Integer.parseInt((String) this.cbxFichas.getSelectedItem());
        int cantJugadores = Integer.parseInt((String) this.cbxJugadores.getSelectedItem());
        presenter.selectGuardar(cantFichas, cantJugadores);
        this.abrirPantJug();
        } catch (Exception e) {
            this.muestraMsjError();
        }
    }

    /**
     * Método que abre la pantalla del jugador
     */
    public void abrirPantJug(){
       presenter.abrirPantallaJugador();
    }
    
    /**
     * Método que muestra un mensaje de error
     */
    public void muestraMsjError() {
        JOptionPane.showMessageDialog(null, "Ha ocurrido un error!!!!!!!", "Error", 
                JOptionPane.ERROR_MESSAGE);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxFichas;
    private javax.swing.JComboBox<String> cbxJugadores;
    private javax.swing.JLabel lblCantFichas;
    private javax.swing.JLabel lblCantJug;
    private javax.swing.JLabel lblConf;
    private javax.swing.JPanel pnlFondo;
    // End of variables declaration//GEN-END:variables
}
