/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author alexa
 */
public class FrmConfPartida extends javax.swing.JFrame {

    /**
     * Creates new form FrmConfPartida
     */
    public FrmConfPartida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        lblConf = new javax.swing.JLabel();
        lblCantFichas = new javax.swing.JLabel();
        lblCantJug = new javax.swing.JLabel();
        btnDosJug = new javax.swing.JButton();
        btnTresJug = new javax.swing.JButton();
        btnCuatroJug = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnCrearPartida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFondo.setBackground(new java.awt.Color(0, 102, 51));

        lblConf.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        lblConf.setForeground(new java.awt.Color(255, 255, 255));
        lblConf.setText("Configuración de la partida");

        lblCantFichas.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        lblCantFichas.setForeground(new java.awt.Color(255, 255, 255));
        lblCantFichas.setText("Cantidad de fichas (2-7)");

        lblCantJug.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        lblCantJug.setForeground(new java.awt.Color(255, 255, 255));
        lblCantJug.setText("Cantidad de jugadores");

        btnDosJug.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnDosJug.setText("2 jugadores");

        btnTresJug.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnTresJug.setText("3 jugadores");

        btnCuatroJug.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnCuatroJug.setText("4 jugadores");

        jComboBox1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7" }));

        btnCrearPartida.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnCrearPartida.setText("Crear partida");

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblConf))
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFondoLayout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(lblCantJug))
                            .addGroup(pnlFondoLayout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTresJug)
                                    .addComponent(btnCuatroJug)
                                    .addComponent(btnDosJug))))
                        .addGap(63, 63, 63)
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCantFichas, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlFondoLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48))))
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(btnCrearPartida)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblConf)
                .addGap(43, 43, 43)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addComponent(lblCantJug)
                        .addGap(18, 18, 18)
                        .addComponent(btnDosJug)
                        .addGap(18, 18, 18)
                        .addComponent(btnTresJug)
                        .addGap(18, 18, 18)
                        .addComponent(btnCuatroJug))
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addComponent(lblCantFichas)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnCrearPartida)
                .addGap(30, 30, 30))
        );

        getContentPane().add(pnlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConfPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConfPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConfPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConfPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConfPartida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearPartida;
    private javax.swing.JButton btnCuatroJug;
    private javax.swing.JButton btnDosJug;
    private javax.swing.JButton btnTresJug;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblCantFichas;
    private javax.swing.JLabel lblCantJug;
    private javax.swing.JLabel lblConf;
    private javax.swing.JPanel pnlFondo;
    // End of variables declaration//GEN-END:variables
}
